name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python Dependency Packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Copy Environment Variables
      run: |
        cp .env.example .env
    - name: Run Django Tests
      run: |
        cd django_openid_auth
        python manage.py test
